# Generated by Django 4.0.3 on 2022-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_likes_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsletterSubscribers',
        ),
        migrations.AlterModelOptions(
            name='newslettersubscribers',
            options={'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
