# Generated by Django 4.0.3 on 2022-04-14 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_rename_bloglike_bloglikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='BlogComments',
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogPost',
        ),
    ]
