# Generated by Django 4.0.3 on 2022-04-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_blogcomment_blogcomments_rename_blog_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'verbose_name': 'Blog Comments', 'verbose_name_plural': 'Blog Comments'},
        ),
        migrations.AlterModelOptions(
            name='bloglikes',
            options={'verbose_name_plural': 'Blog Likes'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
