# Generated by Django 4.0.3 on 2022-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_tags_delete_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_images'),
        ),
    ]
