# Generated by Django 4.0.3 on 2022-04-14 14:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, upload_to='media/myimages/')),
                ('experience', ckeditor.fields.RichTextField()),
                ('projects', ckeditor.fields.RichTextField()),
                ('skills', ckeditor.fields.RichTextField()),
                ('education', ckeditor.fields.RichTextField()),
                ('resume', models.FileField(blank=True, upload_to='media/files/resume/')),
                ('github', models.URLField()),
                ('linkdin', models.URLField()),
                ('reddit', models.URLField()),
                ('telegram', models.URLField()),
                ('quora', models.URLField()),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
