# Generated by Django 4.0.3 on 2022-04-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='reddit',
            new_name='twitter',
        ),
    ]
