# Generated by Django 4.0.3 on 2022-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='linkdin',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='intro',
            field=models.TextField(default='http://t.me/greedypython'),
            preserve_default=False,
        ),
    ]
